server {
    listen 80;
    server_name localhost;

    location /static/ {
        alias /var/ephios/data/public/static/;
    }

    location / {
        proxy_pass http://app:80;
        proxy_set_header Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
