# Generated by Django 5.2.17 on 2026-09-12 22:27

import uuid

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ephios_shift_coordination.models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("core", "0039_alter_userprofile_disabled_notifications"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlannedEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("date", models.DateField()),
                ("original_event_id", models.PositiveIntegerField()),
                (
                    "event",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planning_link",
                        to="core.event",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="PlannedShift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("original_shift_id", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="ephios_shift_coordination.plannedevent",
                    ),
                ),
                (
                    "shift",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="core.shift"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PlanningPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("timezone", models.CharField(max_length=64)),
                ("rules", models.JSONField()),
                ("template_snapshot", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("preparation", "Preparation"),
                            ("survey_open", "Survey open"),
                            ("planning", "Planning"),
                            ("published", "Published"),
                        ],
                        default="preparation",
                        max_length=16,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("creation_key", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("request_digest", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date", "-pk"],
                "permissions": [("manage_planning", "Manage shift planning")],
            },
        ),
        migrations.AddField(
            model_name="plannedevent",
            name="period",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="events",
                to="ephios_shift_coordination.planningperiod",
            ),
        ),
        migrations.CreateModel(
            name="PlanningSettings",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "weekdays",
                    models.JSONField(
                        default=ephios_shift_coordination.models.default_weekdays,
                        verbose_name="Weekdays",
                    ),
                ),
                (
                    "country",
                    models.CharField(default="DE", max_length=2, verbose_name="Holiday country"),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=8, verbose_name="Holiday region"),
                ),
                (
                    "exclude_holidays",
                    models.BooleanField(default=False, verbose_name="Exclude holidays"),
                ),
                (
                    "response_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Response period in days",
                    ),
                ),
                (
                    "reminder_days",
                    models.JSONField(
                        default=ephios_shift_coordination.models.default_reminders,
                        blank=True,
                        verbose_name="Reminder days before deadline",
                    ),
                ),
                (
                    "weekly_limit",
                    models.PositiveSmallIntegerField(default=2, verbose_name="Weekly limit"),
                ),
                (
                    "free_next_day",
                    models.BooleanField(default=True, verbose_name="Keep the next day free"),
                ),
                (
                    "solver_seconds",
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Calculation budget in seconds",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="planning_single_settings"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ServiceTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=254, verbose_name="Title")),
                ("description", models.TextField(blank=True, verbose_name="Description")),
                ("location", models.CharField(max_length=254, verbose_name="Location")),
                (
                    "event_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.eventtype",
                        verbose_name="Event type",
                    ),
                ),
                (
                    "responsible_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="planning_templates",
                        to="auth.group",
                        verbose_name="Responsible groups",
                    ),
                ),
                (
                    "responsible_users",
                    models.ManyToManyField(
                        blank=True, to=settings.AUTH_USER_MODEL, verbose_name="Responsible persons"
                    ),
                ),
                (
                    "visible_for",
                    models.ManyToManyField(to="auth.group", verbose_name="Visible for"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="planningperiod",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="ephios_shift_coordination.servicetemplate",
            ),
        ),
        migrations.CreateModel(
            name="ShiftTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("label", models.CharField(max_length=255, verbose_name="Label")),
                ("meeting_time", models.TimeField(verbose_name="Meeting time")),
                ("start_time", models.TimeField(verbose_name="Start time")),
                ("end_time", models.TimeField(verbose_name="End time")),
                (
                    "end_day_offset",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Same day"), (1, "Next day")],
                        default=0,
                        verbose_name="End day",
                    ),
                ),
                (
                    "minimum",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="Minimum staffing",
                    ),
                ),
                (
                    "maximum",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Maximum staffing"
                    ),
                ),
                (
                    "qualifications",
                    models.ManyToManyField(
                        blank=True, to="core.qualification", verbose_name="Qualifications"
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="ephios_shift_coordination.servicetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="plannedevent",
            constraint=models.UniqueConstraint(
                fields=("period", "date"), name="planning_unique_event_date"
            ),
        ),
        migrations.AddConstraint(
            model_name="planningperiod",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))),
                name="planning_period_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("minimum__gte", 1)), name="planning_shift_minimum"
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("maximum__isnull", True),
                    ("maximum__gte", models.F("minimum")),
                    _connector="OR",
                ),
                name="planning_shift_maximum",
            ),
        ),
        migrations.AddConstraint(
            model_name="shifttemplate",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_day_offset__in", [0, 1])), name="planning_shift_end_day"
            ),
        ),
    ]
