# Generated by Django 5.2.17 on 2026-09-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_userprofile_disabled_notifications"),
        ("ephios_shift_coordination", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planningperiod",
            name="deadline",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="planningperiod",
            name="opened_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="planningperiod",
            name="opened_structure",
            field=models.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name="SurveyResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "maximum",
                    models.PositiveIntegerField(null=True, verbose_name="Personal maximum"),
                ),
                ("notes", models.TextField(blank=True, max_length=4000, verbose_name="Notes")),
                ("submitted_at", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "offered_shifts",
                    models.ManyToManyField(to="ephios_shift_coordination.plannedshift"),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="ephios_shift_coordination.planningperiod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "rating",
                    models.CharField(
                        choices=[
                            ("unavailable", "Unavailable (red)"),
                            ("if_needed", "If needed (yellow)"),
                            ("available", "Available (green)"),
                            ("preferred", "Especially preferred (star)"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "planned_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ephios_shift_coordination.plannedshift",
                    ),
                ),
                (
                    "response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="ephios_shift_coordination.surveyresponse",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NotificationDispatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("kind", models.CharField(max_length=16)),
                ("key", models.CharField(max_length=64)),
                ("skipped", models.BooleanField(default=False)),
                (
                    "notification",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.notification",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ephios_shift_coordination.planningperiod",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("period", "user", "kind", "key"), name="planning_unique_dispatch"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="surveyresponse",
            constraint=models.UniqueConstraint(
                fields=("period", "user"), name="planning_unique_response"
            ),
        ),
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.UniqueConstraint(
                fields=("response", "planned_shift"), name="planning_unique_availability"
            ),
        ),
        migrations.AddConstraint(
            model_name="availability",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("rating__in", ["unavailable", "if_needed", "available", "preferred"])
                ),
                name="planning_valid_rating",
            ),
        ),
    ]
