# Generated by Django 5.2.17 on 2026-09-14 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ephios_shift_coordination",
            "0002_planningperiod_deadline_planningperiod_opened_at_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planningperiod",
            name="draft_fingerprint",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.CreateModel(
            name="RuleOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("draft_version", models.PositiveIntegerField()),
                ("code", models.CharField(max_length=32)),
                ("token", models.CharField(max_length=64)),
                ("facts", models.JSONField()),
                ("reason", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rule_overrides",
                        to="ephios_shift_coordination.planningperiod",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.CreateModel(
            name="DraftAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("original_user_id", models.PositiveIntegerField()),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="draft_assignments",
                        to="ephios_shift_coordination.planningperiod",
                    ),
                ),
                (
                    "planned_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ephios_shift_coordination.plannedshift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("planned_shift", "original_user_id"),
                        name="planning_unique_assignment",
                    )
                ],
            },
        ),
    ]
