# Generated by Django 5.2.17 on 2026-09-15 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ephios_shift_coordination",
            "0003_planningperiod_draft_fingerprint_ruleoverride_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="planningperiod",
            name="publication_snapshot",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="planningperiod",
            name="published_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="planningperiod",
            name="published_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="published_planning_periods",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
