# Generated by Django 5.2.17 on 2026-09-15 23:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0039_alter_userprofile_disabled_notifications"),
        ("ephios_shift_coordination", "0004_planningperiod_publication_snapshot_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="draftassignment",
            name="observer",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="planningperiod",
            name="suggestion",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="planningsettings",
            name="allow_observers",
            field=models.BooleanField(default=False, verbose_name="Allow observers"),
        ),
        migrations.AddField(
            model_name="planningsettings",
            name="minimum_regular",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[django.core.validators.MinValueValidator(1)],
                verbose_name="Regular people per shift with observers",
            ),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="observer_events",
            field=models.ManyToManyField(
                blank=True,
                related_name="observer_responses",
                to="ephios_shift_coordination.plannedevent",
            ),
        ),
        migrations.AlterField(
            model_name="availability",
            name="rating",
            field=models.CharField(
                choices=[
                    ("unavailable", "Unavailable"),
                    ("if_needed", "If needed"),
                    ("available", "Available"),
                    ("preferred", "Preferred"),
                ],
                max_length=16,
            ),
        ),
        migrations.CreateModel(
            name="ObserverParticipation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "participation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_observer",
                        to="core.placeholderparticipation",
                    ),
                ),
                (
                    "planned_shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="observers",
                        to="ephios_shift_coordination.plannedshift",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("planned_shift", "user"), name="planning_unique_observer"
                    )
                ],
            },
        ),
    ]
