# Generated by Django 5.2.17 on 2026-09-18 15:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ephios_shift_coordination.models


class Migration(migrations.Migration):
    dependencies = [
        ("ephios_shift_coordination", "0007_reminders"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AssemblyMinutes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=ephios_shift_coordination.models.minutes_path,
                        validators=[django.core.validators.FileExtensionValidator(["pdf"])],
                        verbose_name="File",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assembly",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="minutes",
                        to="ephios_shift_coordination.assembly",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at", "-pk"],
            },
        ),
    ]
